---
# tasks file for wdijkerman.zabbix
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - zabbix-server
- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - zabbix-server
- name: "Installing the mysql database"
  include: "mysql.yml"
  when:
    - database_type_long == "mysql"
  tags:
    - zabbix-server
- name: "Configure zabbix-server"
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: 0644
  notify:
    - zabbix-server restarted
  tags:
    - zabbix-server
    - init
    - config


- name: "Create include dir zabbix-server"
  file:
    path: "{{ zabbix_server_include }}"
    owner: zabbix
    group: zabbix
    state: directory
    mode: 0755
  tags:
    - zabbix-server
    - init
    - config

- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers
  tags:
    - zabbix-server

- name: "Zabbix-server started"
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
  tags:
    - zabbix-server
