---
# task file for mysql
- name: "Set the correct delegated_dbhost: {{inventory_hostname}} (to support MySQL db deployment on a remote dbhost)"
  set_fact:
    delegated_dbhost: "{{ zabbix_server_dbhost if (zabbix_server_dbhost != 'localhost') else inventory_hostname}}"
  tags:
    - zabbix-server
- name: "MySQL | Create database"
  mysql_db:
    name: "{{ zabbix_server_dbname }}"
    encoding: "{{ zabbix_server_dbencoding }}"
    collation: "{{ zabbix_server_dbcollation }}"
    login_user: "root"
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
    login_unix_socket: "{{mysql_login_unix_socket}}"
    state: present
  when: zabbix_database_creation
  register: zabbix_database_created
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database
    - skip_ansible_lint

- name: "MySQL | Create database user"
  mysql_user:
    name: "{{ zabbix_server_dbuser }}"
    password: "{{ zabbix_server_dbpassword }}"
    priv: "{{ zabbix_server_dbname }}.*:ALL"
    state: present
    login_user: "root"
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
    login_unix_socket: "{{mysql_login_unix_socket}}"
  when: zabbix_database_creation
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database

- name: "Check if we have done files >= 3.0"
  stat:
    path: /etc/zabbix/create.done
  register: done_file
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
  tags:
    - zabbix-server
- name: "Get the file for create.sql >= 3.0"
  shell: ls -1 {{ datafiles_path }}/create.sq*
  changed_when: False
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  register: ls_output_create
  tags:
    - zabbix-server
    - database

- name: "copy file {{ ls_output_create.stdout }} from machine1 to local"
  fetch: src="{{ ls_output_create.stdout }}" dest=/tmp/create.sql.gz flat=yes
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  tags:
    - zabbix-server

- name: copy /tmp/create.sql.gz
  copy:
    src: /tmp/create.sql.gz
    dest: /tmp/
    mode: "ugo=rwx"
  delegate_to: "{{ delegated_dbhost }}"
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  tags:
    - zabbix-server

- name: unarchive /tmp/create.sql
  shell: gunzip -f /tmp/create.sql.gz > /tmp/create.sql 
  args:
    chdir: /tmp
  delegate_to: "{{ delegated_dbhost }}"
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  tags:
    - zabbix-server


- name: "MySQL | Create database in {{delegated_dbhost}} and import file >= 3.0"
  mysql_db:
    name: "{{ zabbix_server_dbname }}"
    encoding: "{{ zabbix_server_dbencoding }}"
    collation: "{{ zabbix_server_dbcollation }}"
    state: import
    # target: "{{ ls_output_create.stdout }}"
    target: "/tmp/create.sql"
    login_user: "root"
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
    login_unix_socket: "{{mysql_login_unix_socket}}"
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database

- name: "Check if we have sql_done files >= 3.0"
  file:
    path: /etc/zabbix/create.done
    state: touch
  when:
    - zabbix_version | version_compare('3.0', '>=')
    - zabbix_database_sqlload
    - not done_file.stat.exists
  tags:
    - zabbix-server
- name: "Get the correct path for the SQL files < 3.0"
  shell: ls -1 {{ datafiles_path }}/create/{{ item }}.sql*
  changed_when: False
  register: ls_output_schema
  with_items:
    - schema
    - images
    - data
  when:
    - zabbix_version | version_compare('3.0', '<')
    - zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "Check if we have done files < 3.0"
  stat:
    path: /etc/zabbix/{{ item }}.done
  register: done_files
  with_items:
    - schema
    - images
    - data
  when:
    - zabbix_version | version_compare('3.0', '<')
    - zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "Create fact if sql_done files exists"
  set_fact:
    sql_files_executed: "{{ sql_files_executed | default({}) | combine({item.item: item.stat}) }}"
  with_items: "{{ done_files.results }}"
  when:
    - zabbix_version | version_compare('3.0', '<')
    - zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "MySQL | Create database and import files < 3.0"
  mysql_db:
    name: "{{ zabbix_server_dbname }}"
    encoding: "{{ zabbix_server_dbencoding }}"
    collation: "{{ zabbix_server_dbcollation }}"
    state: import
    target: "{{ item.stdout }}"
    login_user: "root"
    login_password: "{{mysql_root_password}}"
    login_port: "{{mysql_port}}"
    login_unix_socket: "{{mysql_login_unix_socket}}"
  with_items: "{{ ls_output_schema.results }}"
  when:
    - zabbix_version | version_compare('3.0', '<')
    - zabbix_database_sqlload
    - not sql_files_executed[item.item].exists
  delegate_to: "{{ delegated_dbhost }}"
  tags:
    - zabbix-server
    - database

- name: "Check if we have sql_done files < 3.0"
  file:
    path: /etc/zabbix/{{ item }}.done
    state: touch
  with_items:
    - schema
    - images
    - data
  when:
    - zabbix_version | version_compare('3.0', '<')
    - zabbix_database_sqlload
    - not sql_files_executed[item].exists
  tags:
    - zabbix-server
    - database
