---
# tasks file for zabbix3_2
- name: Create zabbix user group
  group: name={{zabbix_group}} state=present
  tags:
    - zabbix3

- name: Create zabbix user
  become: yes
  user:
    name: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
    system: true
  tags:
    - zabbix3

- name: Install zabbixrequired system packages.
  become: yes
  yum: name={{ item }} state=installed update_cache=true
  with_items: "{{ zabbixserver_packages }}"
  tags:
    - zabbix3

# - name: Download zabbix
#   get_url: url="http://liquidtelecom.dl.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/{{zabbix_version}}/zabbix-{{zabbix_version}}.tar.gz" dest="/home/{{ zabbix_user }}/zabbix-{{zabbix_version}}.tar.gz" mode=0440
#   register: zabbix_download
#   tags:
#     - zabbix3

- name: "create {{zabbix_home}}"
  file:
    path: "{{zabbix_home}}"
    state: directory
    mode: "ug=rwx,o=rx"
    owner: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
  tags:
    - zabbix3

- name: copy zabbix
  copy:
    src: "zabbix-{{zabbix_version}}.tar.gz"
    dest: "{{zabbix_home}}"
    mode: "ug=rwx,o=rx"
    owner: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
  tags:
    - zabbix3


- name:  Extract zabbix  tar
  unarchive: src="{{zabbix_home}}/{{zabbix_tar_file_name}}" dest={{zabbix_home}} copy=no owner={{ zabbix_user }} group={{ zabbix_group }} mode="ug=rwx,o=rx"
  tags:
    - zabbix3

- stat: path={{zabbix_tar_exact_path}}/Makefile
  register: makefile_stat
  tags:
    - zabbix3


- name: already make install
  stat: path="{{zabbix_home}}"
  register: zabbixAlreadyMakeInstall
  tags:
    - zabbix3

- name: Configure Make install
  register: config_makefile
  #when: makefile_stat.stat.exists == False
  shell: "./configure  --prefix={{zabbix_home}} --enable-web --with-net-snmp --with-libcurl --with-libcurl2 --with-ssh2 --with-unixodbc --with-mysql"
  when: zabbixAlreadyMakeInstall.stat.exists == False
  args:
    chdir: "{{zabbix_tar_exact_path}}/"
  tags:
    - zabbix3

- name: Make install
  become: yes
  shell: make install
  args:
    chdir: "{{zabbix_tar_exact_path}}/"
  when: zabbixAlreadyMakeInstall.stat.exists == False
  tags:
    - zabbix3

- name: zabbix.conf
  template:
    src: zabbix_server_nginx.conf
    dest: "{{nginx_servers_path}}"
    owner: root
    group: root
    mode: "ug=rwx,o=rx"
  delegate_to: "{{delegated_nginx_host}}"
  tags:
    - php-openresty
  notify: restart nginx



# - name: "config zabbix {{zabbix_tar_exact_path}}/conf/"
#   template:
#     src: zabbix_server.conf
#     dest: "{{zabbix_tar_exact_path}}/conf/"
#     owner: "{{zabbix_user}}"
#     group: "{{zabbix_group}}"
#     mode: "ug=rwx,o=rx"
#   tags:
#     - zabbix3

- name: "config zabbix {{zabbix_frontends_path}}/conf"
  template:
    src: zabbix-setup.php
    dest: "{{zabbix_frontends_path}}/conf/zabbix.conf.php"
    owner: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
    mode: "ug=rwx,o=rx"
  tags:
    - zabbix3

# - name: copy zabbix php
#   shell: "cp -r {{zabbix_tar_exact_path}}/frontends/php/ {{zabbix_frontends_path}}"
#   become: yes
#   tags:
#     - zabbix3

- name: set owner
  file:
    path: "{{zabbix_frontends_path}}"
    recurse: true
    owner: "{{zabbix_user}}"
    group: "{{zabbix_group}}"
    mode: "ug=rwx,o=rx"
  tags:
    - zabbix3

- meta: flush_handlers
  tags:
    - zabbix3
